---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github
  namespace: flux-system
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: cert-manager
      name: "*"
    - kind: HelmRelease
      namespace: kube-system
      name: "*"
    - kind: HelmRelease
      namespace: metallb
      name: "*"
    - kind: HelmRelease
      namespace: monitoring
      name: "*"
    - kind: HelmRelease
      namespace: traefik
      name: "*"
  suspend: false